### PR TITLE
Add check for isTree

### PR DESCRIPTION
**Pull request by ericpoe**
This is an explicit check to see if the node is a tree or sub-tree. One could argue that
if the node is not a leaf, it is implicitly a tree. Yet, checking for `!$node->isLeaf()`
is an odd way to see if the node has children.

This paves the way to ask if this node is a tree & a root? a tree & a sub-tree? or a leaf?

### CODE REVIEW

**Comment by nicmart** [comment]
For me also a leaf is a tree, maybe the method should be called `isInternalNode`.
I don't see the point instead in elevating composite checks at api level, the combinations can be a lot, and I want to maintain the Node api as small as possible.

**Comment by localheinz** [comment]
@ericpoe 

As far as I remember from *Computerorientierte Mathematik*, a single node is a tree by itself, too.

**Comment by ericpoe** [comment]
@nicmart and @localheinz Thanks for your feedback. I am changing this PR to check instead if the node is an internal node, as recommended by @nicmar. I have looked through my algorithm books from my CS work in school, and I cannot find a formal definition for a tree versus a node (https://en.wikipedia.org/wiki/Introduction_to_Algorithms & http://algs4.cs.princeton.edu/home/). However, when looking at the [National Institute of Standards and Technology (USA)](http://xlinux.nist.gov/dads//HTML/tree.html) definition, I see that "internal node" is closest to what I was trying to convey.

See commit: 0eef605

**Comment by nicmart** [comment]
Why you put the check that doesn't allow the root to be internal?

**Comment by ericpoe** [comment]
I did more looking into trees, internal/external nodes, etc, and even contacted a former professor of mine. A leaf is an external node; root & subtrees are internal nodes. So, if it's not a leaf, it's an internal node.

From this deeper look, I'm not seeing much value in what is essentially an alias to "!isLeaf" other than to be more explicit. And if we have an "isInternalNode" method, should we have an "isExternalNode" method that is an alias to "isLeaf" too?

## BC Break ##
Where I am seeing value is in the redefinition of the root node as an internal node, not as a leaf. When planting a seed, the root emerges before the leaf -- so, too, in data trees. As such, this redefines the leaf by adding the caveat that it is not a root node, too.

**Comment by ericpoe** [comment]
Thanks for your feedback on the above. I'm going to close this PR since it doesn't fulfil the original intent of the PR. The BC break is important and should be in its own PR with its own discussion thread. Cheers!

**Pull request closed without merging**
