### PR TITLE
Support for PHP 8.0

### PR DESCRIPTION
**Pull request by pascalbaljet**

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi @nicmart a package of ours is waiting for this package to support PHP 8.0

If possible, could you merge this in soon?

Thank you for your work creating this package 👍

**Comment by nicmart** [comment]
Hi @freekmurze, I am not the active maintainer of the library anymore.
@localheinz kindly offered to help with the library, so I am redirecting you to him.

**Comment by localheinz** [comment]
@freekmurze @nicmart @pascalbaljet 

Taking a look later!

👀

**Comment by freekmurze** [comment]
Much appreciated! 

I don't want to pressure you in any way, so if you can't find the time, that's ok. I can wait 👍

**Comment by localheinz** [comment]
Thank you, @pascalbaljet!

**Comment by freekmurze** [comment]
That was fast! Thanks!

**Comment by pascalbaljet** [comment]
Thanks!

**Pull request merged**
