### PR TITLE
Fix: Update README

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] fixes a few unrelated issues in `README.md`
* [x] updates `README.md` with notes about tree traversal

Follows #24.

### CODE REVIEW

**Comment by localheinz** [comment]
@nicmart 

I have updated `README-md`, maybe you want to merge this before you tag?

**Comment by nicmart** [comment]
Perfect, do you mind to squash the commits? Thanks

**Comment by localheinz** [comment]
@nicmart 

:+1: There you have it!

**Comment by nicmart** [comment]
Thanks!

**Pull request merged**
